pref("include-firstauthors-in-list", true);
pref("first_n_authors", 1);
pref("include-lastauthor-in-list", true);
pref("firstnamestyle", "full");
pref("namestyle", "auto");
pref("sep-intra-author", " ");
pref("sep-intra-author-cjk", "");
pref("sep-inter-author", ", ");
pref("sep-omitted-authors", "...");
pref("indicator-for-lastauthor", "†");
pref("indicator-position", "after");
pref("openalex-api-key", "");
pref("crossref-email", "");
pref("grobid-url", "http://127.0.0.1:8070");
pref("enable-grobid", true);
pref("merge-parent-institution", true);
pref("full-count", true);
pref("deepseek-api-key", "");
pref("deepseek-model", "deepseek-v4-flash");
